DROP SEQUENCE seq_episode_id;
DROP SEQUENCE seq_volume_id;
DROP SEQUENCE seq_chapter_id;
DROP SEQUENCE seq_author_id;
DROP SEQUENCE seq_medium_id;
DROP SEQUENCE seq_ilustrator_id; 

CREATE SEQUENCE seq_episode_id
    MINVALUE 0
    MAXVALUE 10000000000
    START WITH 0
    INCREMENT BY 1
    CACHE 20;
    
CREATE SEQUENCE seq_volume_id
    MINVALUE 0
    MAXVALUE 10000000000
    START WITH 0
    INCREMENT BY 1
    CACHE 20;
    
CREATE SEQUENCE seq_chapter_id
    MINVALUE 0
    MAXVALUE 10000000000
    START WITH 0
    INCREMENT BY 1
    CACHE 20;

    
CREATE SEQUENCE seq_author_id
    MINVALUE 0
    MAXVALUE 10000000000
    START WITH 0
    INCREMENT BY 1
    CACHE 20;

CREATE SEQUENCE seq_medium_id
    MINVALUE 0
    MAXVALUE 10000000000
    START WITH 0
    INCREMENT BY 1
    CACHE 20;    

CREATE SEQUENCE seq_ilustrator_id
    MINVALUE 0
    MAXVALUE 10000000000
    START WITH 0
    INCREMENT BY 1
    CACHE 20;